### PR TITLE
Add environment var to specify AWS Athena workgroup

### LINKED ISSUE #99: [Feature] Specify Athena workgroup as an environment variable
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing Dekart functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When submitting queries to be ran by AWS Athena, one optional parameter is the [workgroup](https://docs.aws.amazon.com/athena/latest/ug/manage-queries-control-costs-with-workgroups.html) that will run the query. Specifying the workgroup can have a material impact on a query, since it affects things like IAM permissions, the Athena engine version being used, etc.

I would propose that a new environment variable like `DEKART_ATHENA_WORKGROUP` be created and used when starting a new query execution, and alternatively use the default value of `primary` when not set, since that's what's implicitly being used now.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

Any Dekart users that utilize AWS Athena for their analytics engine.

### Are you interested in contributing this feature?

Yes, I can probably add it. Wanted to make sure this is something that wouldn't be rejected for whatever reason before starting it.

### Anything else?

Wanted to add a thank you for all of the work that's previously been done, Dekart is a great project!

### PR DESCRIPTION
**Pull request by seanlane**
resolves #99 

Adds an environment variable `DEKART_ATHENA_WORKGROUP`, and then attempts to use that value for specifying the Athena workgroup used when starting a query execution. If the value is not set or is empty, the default value will be a `nil` string pointer. 

When the `WorkGroup` field of the `StartQueryExecutionInput` struct is a nil pointer, Athena uses the `primary` workgroup that exists within all AWS accounts (since the `primary` workgroup cannot be renamed or deleted, per AWS documentation [here](https://docs.aws.amazon.com/athena/latest/ug/workgroups-create-update-delete.html)). 

This is the current, implicit behavior since `WorkGroup` was not being utilized until now. If the value is not set, a warning will be emitted when an Athena query is executed, for example:

Screen Shot 2023-05-09 at 10 40 54 AM

If the specified workgroup does not exist, the query will fail, but I consider that to be expected behavior.

When the environment variable is set, a debug message is emitted when an Athena query, for example:

Screen Shot 2023-05-09 at 10 40 20 AM

### CODE REVIEW

**Comment by delfrrr** [comment]
Great, appreciate!

**Comment by delfrrr** [comment]
@seanlane feature available in `v0.12.2-rc.1`

**Comment by delfrrr** [comment]
Hey, @seanlane, join our [Slack](https://bit.ly/dekart-slack), will be happy chatting with you and having your feedback!

**Comment by seanlane** [comment]
will do, thanks for the invite

**Pull request merged**
